Añadida 2 reglas rego para su correcto funcionamiento además de actualizar el CHANGELOG.md

diff --git a/.github/workflows/cicd.yml b/.github/workflows/cicd.yml
--- a/.github/workflows/cicd.yml
+++ b/.github/workflows/cicd.yml
@@ -91,6 +91,20 @@ jobs:
           echo "Resultado Region Check: $RESULT"
           echo "$RESULT" | grep -q "true" || (echo "ERROR: Región de AWS no permitida." && exit 1)
 
+      # --- NUEVAS POLÍTICAS OPA ---
+      - name: OPA Policy Evaluation - SSH Check
+        run: |
+          RESULT=$(opa eval -i tfplan.json -d terraform_ssh_check.rego "data.terraform.ssh_check.allow" --format json)
+          echo "Resultado SSH Check: $RESULT"
+          echo "$RESULT" | grep -q "true" || (echo "ERROR: OPA DETECTÓ ACCESO SSH PÚBLICO (0.0.0.0/0). Despliegue abortado." && exit 1)
+
+      - name: OPA Policy Evaluation - Instance Type Check
+        run: |
+          RESULT=$(opa eval -i tfplan.json -d terraform_instance_type_check.rego "data.terraform.instance_type_check.allow" --format json)
+          echo "Resultado Instance Type Check: $RESULT"
+          echo "$RESULT" | grep -q "true" || (echo "ERROR: OPA DETECTÓ INSTANCIA DISTINTA A t2.micro. Despliegue abortado." && exit 1)
+      # -----------------------------
+
       - name: Terraform Apply
         run: terraform apply -auto-approve tfplan
 
